Ffo courses access
SIGL-SIWEB/new-intra pull request #25
Opened 2021-05-25 09:19 UTC by Naorid

https://trello.com/c/DiHFYH8i/71-permettre-%C3%A0-ffo-de-modifier-les-notes-de-toutes-les-mati%C3%A8res

2021-05-25 18:35 UTC, MaxCollo commented on src/app/notes/teacher_grade/teacher_grade.component.ts
> +        if (NavigationComponent.getToken().preferred_username == "fourdr_f") {
Vérifier le rôle de ~Chef de majeur plutôt que le login

2021-05-25 19:02 UTC, MaxCollo requested changes
Vu avec @Kewynhe, il faut créer le rôle chef de majeure et l'utiliser pour vérifier l'utilisateur à la place du login "fourdr_f"

2021-05-26 21:42 UTC, Naorid commented on src/app/notes/teacher_grade/teacher_grade.component.ts
> +        if (NavigationComponent.getToken().preferred_username == "fourdr_f") {
Salut Maxime !
J'ai fait un commit pour changer ca :)
https://github.com/SIGL-SIWEB/new-intra/commit/427c761386c5f6983babef0724838a3a3b321513

2021-05-26 21:43 UTC, Naorid commented on src/app/notes/teacher_grade/teacher_grade.component.ts
> +        if (NavigationComponent.getToken().preferred_username == "fourdr_f") {
(Le role "MajorLeader" a été ajouté dans le keycloak et donné a fourdr_f)

2021-05-26 21:43 UTC, MaxCollo commented on src/app/notes/teacher_grade/teacher_grade.component.ts
> +        if (NavigationComponent.getToken().preferred_username == "fourdr_f") {
Super Dorian !
Je valide la résolution et tu peux merge ;)

2021-05-26 21:44 UTC, MaxCollo approved these changes

2021-05-26 21:46 UTC, merged