Moyennes et Ecart-types dans le xlsx
SIGL-SIWEB/new-intra pull request #30
Opened 2021-05-29 15:19 UTC by MaxCollo

### Added
courseMean et courseSD dans le type **GradesAsXLSX**
La moyenne et l'écart-type de chaque cours dans le xlsx

### Warning
La validation doit se faire en simultané avec la PR de **note_back**

### Trello
https://trello.com/c/ZE8sZlnh

2021-05-29 20:13 UTC, Kewynhe requested changes

2021-05-29 20:13 UTC, Kewynhe commented on src/app/notes/service/exportAsXLSX.ts
> +        sheet[grade_index++].push(course.courseSD);
"courseSD", Qu'est ce que SD ?  Etre plus explicite sur le sens de SD

2021-05-29 20:13 UTC, Kewynhe commented on src/app/notes/types/types.ts
>      coefficient: number,
Pourquoi "coefficient" et pas "courseCoefficient" comme la ligne 65 à 68 ?
Même réflexion pour les autres attributs.

2021-05-30 18:11 UTC, Naorid commented
Export XLSX : même coms que dans le back
Nom du fichier d'export (test.xlsx)
Variables (ex Promo) a mettre dans un dot env
'N/A' a changer en '-'
Nom de fonction plus explicite (s2ab)
Dans l'interface gradesAsXSLX, les variable concernant les cours : mettre Course devant le nom
Changer le nom de l'interface vu que ca contient pas que des grades

2021-05-30 18:25 UTC, MaxCollo commented on src/app/notes/types/types.ts
>      coefficient: number,
Done

2021-05-30 18:26 UTC, Kewynhe approved these changes

2021-05-30 18:26 UTC, merged